config/routes.rb
Djors::Application.routes.draw do
  

  resources :menu_types

  resources :employees

  resources :services

  resources :menus do
    resources :menu_recipes
  end

  resources :reservations do
     resources :reserve_function_rooms
  end

  resources :function_rooms

  resources :recipes

  resources :packages do
      resources :package_employees
  end

  resources :recipe_types

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_one :package
	has_many :package_employees
end

app/models/function_room.rb
class FunctionRoom < ActiveRecord::Base
	has_many :reserve_function_rooms
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :recipes
	has_many :menu_recipes
end

app/models/menu_recipe.rb
class MenuRecipe < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :menu
end

app/models/menu_type.rb
class MenuType < ActiveRecord::Base
	belongs_to :menu
end

app/models/package.rb
class Package < ActiveRecord::Base
	has_many :employees
	has_many :package_employees
end

app/models/package_employee.rb
class PackageEmployee < ActiveRecord::Base
	belongs_to :employee
	belongs_to :package
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_one :menu
	has_one :recipe_type
end

app/models/recipe_type.rb
class RecipeType < ActiveRecord::Base
	belongs_to :recipe
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :reserve_function_rooms
	has_many :function_rooms, :through =>:reserve_function_rooms
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/package_employees_controller.rb
class PackageEmployeesController < ApplicationController
  # GET /package_employees
  # GET /package_employees.json
  def index
    @package_employees = PackageEmployee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @package_employees }
    end
  end

  # GET /package_employees/1
  # GET /package_employees/1.json
  def show
    @package_employee = PackageEmployee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @package_employee }
    end
  end

  # GET /package_employees/new
  # GET /package_employees/new.json
  def new
    @package = Package.find(params[:package_id])
    @package_employee = @package.package_employees.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @package_employee }
    end
  end

  # GET /package_employees/1/edit
  def edit
    @package_employee = PackageEmployee.find(params[:id])
  end

  # POST /package_employees
  # POST /package_employees.json
  def create
    @package = Package.find(params[:package_id])
    @package_employee = @package.package_employees.build(params[:package_employee])
    respond_to do |format|
      if @package_employee.save
        format.html { redirect_to @package, notice: 'Package employee was successfully created.' }
        format.json { render json: @package_employee, status: :created, location: @package_employee }
      else
        format.html { render action: "new" }
        format.json { render json: @package_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /package_employees/1
  # PUT /package_employees/1.json
  def update
    @package_employee = PackageEmployee.find(params[:id])

    respond_to do |format|
      if @package_employee.update_attributes(params[:package_employee])
        format.html { redirect_to @package_employee, notice: 'Package employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @package_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_employees/1
  # DELETE /package_employees/1.json
  def destroy
    @package_employee = PackageEmployee.find(params[:id])
    @package_employee.destroy

    respond_to do |format|
      format.html { redirect_to package_employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/menu_recipes_helper.rb
module MenuRecipesHelper
end

app/helpers/menu_types_helper.rb
module MenuTypesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/package_employees_helper.rb
module PackageEmployeesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/recipe_types_helper.rb
module RecipeTypesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/package_employees/_form.html.erb
<%= form_for([package,package_employee]) do |f| %>
  <% if @package_employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@package_employee.errors.count, "error") %> prohibited this package_employee from being saved:</h2>

      <ul>
      <% @package_employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :employee ,"Employee"%>
  <%= f.collection_select :employee_id, Employee.all,:id,:name,:prompt => true%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_employees/edit.html.erb
<h1>Editing package_employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @package_employee %> |
<%= link_to 'Back', package_employees_path %>

app/views/package_employees/index.html.erb
<h1>Listing package_employees</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @package_employees.each do |package_employee| %>
  <tr>
    <td><%= link_to 'Show', package_employee %></td>
    <td><%= link_to 'Edit', edit_package_employee_path(package_employee) %></td>
    <td><%= link_to 'Destroy', package_employee, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Package employee', new_package_employee_path %>

app/views/package_employees/new.html.erb
<h1>New package_employee</h1>

<%= render 'form' , :package => @package , :package_employee => @package_employee%>

app/views/package_employees/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_package_employee_path(@package_employee) %> |
<%= link_to 'Back', package_employees_path %>