config/routes.rb
Djors::Application.routes.draw do
  

  resources :menu_types

  resources :employees

  resources :services

  resources :menus do
    resources :menu_recipes
  end

  resources :reservations do
     resources :reserve_function_rooms
  end

  resources :function_rooms

  resources :recipes

  resources :packages do
      resources :package_employees
  end

  resources :recipe_types

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_one :package
	has_many :package_employees
end

app/models/function_room.rb
class FunctionRoom < ActiveRecord::Base
	has_many :reserve_function_rooms
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :recipes
	has_many :menu_recipes
end

app/models/menu_recipe.rb
class MenuRecipe < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :menu
end

app/models/menu_type.rb
class MenuType < ActiveRecord::Base
	belongs_to :menu
end

app/models/package.rb
class Package < ActiveRecord::Base
	has_many :employees
	has_many :package_employees
end

app/models/package_employee.rb
class PackageEmployee < ActiveRecord::Base
	belongs_to :employee
	belongs_to :package
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_one :menu
	has_one :recipe_type
end

app/models/recipe_type.rb
class RecipeType < ActiveRecord::Base
	belongs_to :recipe
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :reserve_function_rooms
	has_many :function_rooms, :through =>:reserve_function_rooms
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/menu_types_controller.rb
class MenuTypesController < ApplicationController
  # GET /menu_types
  # GET /menu_types.json
  def index
    @menu_types = MenuType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menu_types }
    end
  end

  # GET /menu_types/1
  # GET /menu_types/1.json
  def show
    @menu_type = MenuType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu_type }
    end
  end

  # GET /menu_types/new
  # GET /menu_types/new.json
  def new
    @menu_type = MenuType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu_type }
    end
  end

  # GET /menu_types/1/edit
  def edit
    @menu_type = MenuType.find(params[:id])
  end

  # POST /menu_types
  # POST /menu_types.json
  def create
    @menu_type = MenuType.new(params[:menu_type])

    respond_to do |format|
      if @menu_type.save
        format.html { redirect_to @menu_type, notice: 'Menu type was successfully created.' }
        format.json { render json: @menu_type, status: :created, location: @menu_type }
      else
        format.html { render action: "new" }
        format.json { render json: @menu_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menu_types/1
  # PUT /menu_types/1.json
  def update
    @menu_type = MenuType.find(params[:id])

    respond_to do |format|
      if @menu_type.update_attributes(params[:menu_type])
        format.html { redirect_to @menu_type, notice: 'Menu type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_types/1
  # DELETE /menu_types/1.json
  def destroy
    @menu_type = MenuType.find(params[:id])
    @menu_type.destroy

    respond_to do |format|
      format.html { redirect_to menu_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/menu_recipes_helper.rb
module MenuRecipesHelper
end

app/helpers/menu_types_helper.rb
module MenuTypesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/recipe_types_helper.rb
module RecipeTypesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/menu_types/_form.html.erb
<%= form_for(@menu_type) do |f| %>
  <% if @menu_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_type.errors.count, "error") %> prohibited this menu_type from being saved:</h2>

      <ul>
      <% @menu_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_types/edit.html.erb
<h1>Editing menu_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_type %> |
<%= link_to 'Back', menu_types_path %>

app/views/menu_types/index.html.erb
<h1>Listing menu_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menu_types.each do |menu_type| %>
  <tr>
    <td><%= menu_type.name %></td>
    <td><%= menu_type.description %></td>
    <td><%= link_to 'Show', menu_type %></td>
    <td><%= link_to 'Edit', edit_menu_type_path(menu_type) %></td>
    <td><%= link_to 'Destroy', menu_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu type', new_menu_type_path %>

app/views/menu_types/new.html.erb
<h1>New menu_type</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_types_path %>

app/views/menu_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu_type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @menu_type.description %>
</p>


<%= link_to 'Edit', edit_menu_type_path(@menu_type) %> |
<%= link_to 'Back', menu_types_path %>